'use strict';
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const line=(x1,y1,x2,y2,c='#29465f',w=4)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${w}"/>`;
const text=(x,y,t,c)=>`<text x="${x}" y="${y}" text-anchor="middle" ${c?`style="fill:${c}"`:''}>${t}</text>`;
const defs=`<defs><marker id="blue" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#1465df"/></marker><marker id="orange" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#c45110"/></marker></defs>`;
function arrow(x1,y1,x2,y2,color='blue'){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color==='blue'?'#1465df':'#c45110'}" stroke-width="3" marker-end="url(#${color})"/>`}
function resistor(x,y,len=80){let pts=`${x},${y} ${x+10},${y}`;for(let i=0;i<6;i++)pts+=` ${x+15+i*(len-30)/5},${y+(i%2?-10:10)}`;pts+=` ${x+len-10},${y} ${x+len},${y}`;return `<polyline points="${pts}" stroke="#29465f" stroke-width="4" fill="none"/>`}
function battery(x,y,positiveRight=true){return line(x-9,y- (positiveRight?14:24),x-9,y+(positiveRight?14:24))+line(x+9,y-(positiveRight?24:14),x+9,y+(positiveRight?24:14))+text(x-16,y-35,positiveRight?'−':'+')+text(x+18,y-35,positiveRight?'+':'−')}
let travel=1,current=1,selected='b20',hiddenSigns=false;
const componentNames={r2:'Resistencia de 2 Ω',r6:'Resistencia de 6 Ω',b20:'Batería de 20 V',b4:'Batería de 4 V'};
function loopTerms(t=travel,i=current){const s=t===i?-1:1;return{r2:s,r6:s,b20:t,b4:-t}}
function describe(id){const terms=loopTerms(),sign=terms[id];if(id[0]==='b'){const v=id==='b20'?20:4;return `${sign>0?'Entras por − y sales por +: el potencial sube.':'Entras por + y sales por −: el potencial baja.'} Aporte: ${sign>0?'+':'−'}${v} V.`}return `${travel===current?'Recorres la resistencia a favor de la corriente supuesta: el potencial baja.':'Recorres la resistencia en contra de la corriente supuesta: el potencial sube.'} Aporte: ${sign>0?'+':'−'}${id==='r2'?2:6}I.`}
function renderLoop(){let svg=defs;svg+=line(85,115,180,115)+resistor(180,115)+line(260,115,371,115)+battery(380,115)+line(389,115,530,115)+line(530,115,530,315)+line(530,315,425,315)+resistor(345,315)+line(345,315,224,315)+battery(215,315)+line(206,315,85,315)+line(85,315,85,115);
svg+=text(220,85,'2 Ω')+text(380,165,'20 V')+text(385,365,'6 Ω')+text(215,365,'4 V');
svg+=travel===1?arrow(180,40,300,40)+arrow(575,175,575,255):arrow(300,40,180,40)+arrow(575,255,575,175);svg+=text(440,44,travel===1?'Recorrido horario':'Recorrido antihorario','#1465df');svg+=current===1?arrow(100,220,100,145,'orange'):arrow(100,145,100,220,'orange');svg+=text(140,205,'I','#c45110');
const positions={r2:[220,115],r6:[385,315],b20:[380,115],b4:[215,315]};for(const[id,[x,y]]of Object.entries(positions)){svg+=`<g class="hit" tabindex="0" role="button" aria-label="${componentNames[id]}" data-component="${id}"><rect class="hitbox" x="${x-48}" y="${y-30}" width="96" height="60" rx="10" fill="${selected===id?'#1465df':'transparent'}" fill-opacity=".09" stroke="${selected===id?'#1465df':'transparent'}"/></g>`}
$('#loop').innerHTML=`<svg viewBox="0 0 630 400" role="img" aria-label="Malla con baterías de 20 y 4 voltios y resistencias de 2 y 6 ohmios">${svg}</svg>`;
const terms=loopTerms(),fmt=(id,v)=>`${terms[id]>0?'+':'−'} ${v}`;$('#equation').textContent=hiddenSigns?'¿Qué signo lleva cada término? Selecciona un componente.':`${fmt('b20','20')} ${fmt('r2','2I')} ${fmt('r6','6I')} ${fmt('b4','4')} = 0`;
const computed=current*2;$('#detail').innerHTML=`<span class="eyebrow">COMPONENTE SELECCIONADO</span><h2>${componentNames[selected]}</h2><div class="result">${hiddenSigns?'¿+ o −?':(terms[selected]>0?'+':'−')+(selected[0]==='b'?(selected==='b20'?'20 V':'4 V'):(selected==='r2'?'2I':'6I'))}</div><p>${hiddenSigns?'Decide primero. Desmarca «Ocultar signos» para comprobar.':describe(selected)}</p><hr><p><strong>Solución con tu flecha:</strong> I = ${computed} A.</p><p>${computed<0?'El signo negativo indica que la corriente real es contraria a tu flecha: es horaria.':'La corriente real coincide con tu flecha: es horaria.'}</p><p class="hint">La resistencia R es positiva; el signo pertenece al cambio de voltaje.</p>`;
$$('[data-component]').forEach(el=>{const go=()=>{selected=el.dataset.component;renderLoop()};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}})}
$$('[name=travel]').forEach(el=>el.onchange=()=>{travel=Number(el.value);renderLoop()});$$('[name=current]').forEach(el=>el.onchange=()=>{current=Number(el.value);renderLoop()});$('#hide').onchange=e=>{hiddenSigns=e.target.checked;renderLoop()};
$$('.tab').forEach(el=>el.onclick=()=>{$$('.view').forEach(v=>v.hidden=v.id!==el.dataset.tab);$$('.tab').forEach(b=>b.classList.toggle('active',b===el))});
const signQs=[{q:'Cruzas una batería de − a +. ¿Qué signo tiene su aporte?',a:1,e:'El potencial sube: +ε.'},{q:'Cruzas una batería de + a −. ¿Qué signo tiene su aporte?',a:-1,e:'El potencial baja: −ε.'},{q:'La corriente va a la derecha y recorres la resistencia a la derecha. ¿Qué signo usas?',a:-1,e:'Vas a favor de I: −IR.'},{q:'La corriente va a la derecha y recorres la resistencia a la izquierda. ¿Qué signo usas?',a:1,e:'Vas contra I: +IR.'},{q:'Recorres hacia arriba una resistencia cuya corriente apunta hacia abajo. ¿Qué signo usas?',a:1,e:'Recorrido y corriente son opuestos: +IR.'},{q:'Recorres hacia abajo una resistencia cuya corriente apunta hacia abajo. ¿Qué signo usas?',a:-1,e:'Recorrido y corriente coinciden: −IR.'}];let sq=0;function signQuestion(){$('#sign-question').textContent=signQs[sq].q;$('#sign-feedback').textContent=''}$$('[data-sign]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.sign)===signQs[sq].a;$('#sign-feedback').className=ok?'good':'bad';$('#sign-feedback').textContent=(ok?'Correcto. ':'Revisa el recorrido. ')+signQs[sq].e});$('#next-sign').onclick=()=>{sq=(sq+1)%signQs.length;signQuestion()};
const nodeMap={a:0,b:0,c:1,d:1,f:1,e:2,g:3};const colors=['#168078','#b5530b','#7444bb','#1769d1'];let nodeSelected=null,allNodes=false;
function renderNodes(){const nc=n=>allNodes||nodeSelected===n?colors[n]:'#29465f';let s=defs;
s+=line(150,85,150,160,nc(2))+line(150,240,150,365,nc(0))+line(150,365,280,365,nc(0))+line(360,365,480,365,nc(1))+line(480,365,480,85,nc(1))+line(150,85,311,85,nc(2))+battery(320,85,false)+line(329,85,480,85,nc(1));
s+=`<g transform="translate(150,160) rotate(90)">${resistor(0,0)}</g>`+text(98,208,'4 Ω')+line(150,240,201,240,nc(0))+battery(210,240,true)+line(219,240,280,240,nc(3))+resistor(280,240)+line(360,240,480,240,nc(1))+resistor(280,365)+text(320,410,'2 Ω')+text(320,210,'6 Ω')+text(210,290,'10 V')+text(320,45,'14 V');
s+=arrow(382,219,440,219,'orange')+text(410,199,'I₁','#c45110')+arrow(515,120,515,205,'orange')+text(552,168,'I₂','#c45110')+arrow(515,266,515,338,'orange')+text(552,311,'I₃','#c45110');
const pos={e:[150,85],f:[480,85],b:[150,240],g:[250,240],c:[480,240],a:[150,365],d:[480,365]};for(const[p,[x,y]]of Object.entries(pos)){s+=`<g class="hit" role="button" tabindex="0" aria-label="Punto ${p}" data-point="${p}"><circle class="hitbox" cx="${x}" cy="${y}" r="23" fill="${nc(nodeMap[p])}" fill-opacity=".12"/><circle cx="${x}" cy="${y}" r="6" fill="${nc(nodeMap[p])}"/>${text(x+(x<300?-30:30),y+7,p)}</g>`}
$('#node-circuit').innerHTML=`<svg viewBox="0 0 630 445" role="img" aria-label="Circuito de tres ramas con puntos a b c d e f g seleccionables">${s}</svg>`;
$$('[data-point]').forEach(el=>{const go=()=>{allNodes=false;nodeSelected=nodeMap[el.dataset.point];renderNodes();const groups=['a y b','c, d y f','e','g'];$('#node-detail').textContent=`Punto ${el.dataset.point}: nodo formado por ${groups[nodeSelected]}. ${nodeSelected<2?'Es un nodo esencial: conecta tres ramas.':'No es esencial: conecta dos elementos.'}`};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}})}
$('#show-nodes').onclick=()=>{allNodes=true;nodeSelected=null;renderNodes();$('#node-detail').textContent='Hay 4 nodos eléctricos: {a,b}, {c,d,f}, {e} y {g}. Dos son esenciales: {a,b} y {c,d,f}. g está entre la batería de 10 V y la resistencia de 6 Ω.'};$('#reset-nodes').onclick=()=>{allNodes=false;nodeSelected=null;renderNodes();$('#node-detail').textContent='Selecciona un punto para seguir el cable.'};
const nodeQs=[['a','b'],['c','f'],['b','e'],['b','g'],['f','d'],['a','d']];let nq=0;function nodeQuestion(){$('#node-question').textContent=`¿${nodeQs[nq][0]} y ${nodeQs[nq][1]} pertenecen al mismo nodo?`;$('#node-feedback').textContent=''}$$('[data-node-answer]').forEach(b=>b.onclick=()=>{const[a,z]=nodeQs[nq],same=nodeMap[a]===nodeMap[z],ok=(b.dataset.nodeAnswer==='true')===same;$('#node-feedback').className=ok?'good':'bad';$('#node-feedback').textContent=(ok?'Correcto. ':'Inténtalo siguiendo los cables. ')+(same?'Están unidos solo por cable ideal.':'Entre esos puntos hay al menos un componente; no son el mismo nodo.')});$('#next-node').onclick=()=>{nq=(nq+1)%nodeQs.length;nodeQuestion()};
const problems=[{title:'Una malla: empieza por los signos',tag:'Nivel 1',desc:'Batería de 12 V y resistencias de 2 Ω y 4 Ω en serie. Recorres de − a + la batería y sigues la corriente horaria por ambas resistencias.',value:2,unit:'A',ask:'¿Cuánto vale I?',steps:['Elige I horaria y recorre en sentido horario.','Batería: +12. Resistencias: −2I y −4I.','Malla: 12 − 2I − 4I = 0.','12 = 6I → I = 2 A.','Comprobación: las caídas son 4 V y 8 V; suman 12 V.']},{title:'Dos baterías: simulacro 2, ejercicio 2',tag:'Nivel 2',desc:'Usa el circuito de la pestaña Signos: 20 V arriba, 4 V abajo, ambas con + a la derecha; resistencias de 2 Ω y 6 Ω. Supón I horaria.',value:2,unit:'A',ask:'¿Cuánto vale I con esa flecha?',steps:['Recorrido horario: arriba de izquierda a derecha, abajo de derecha a izquierda.','Batería superior: +20 V. Batería inferior: −4 V.','Ambas resistencias se recorren a favor de I: −2I y −6I.','20 − 2I − 6I − 4 = 0 → 16 = 8I.','I = 2 A, horaria. Caída total IR = 2(2+6) = 16 V; en el recorrido aporta −16 V.']},{title:'Una corriente negativa no es un error',tag:'Nivel 2',desc:'Mismo circuito anterior, pero ahora supones la corriente antihoraria y recorres también en sentido antihorario.',value:-2,unit:'A',ask:'¿Qué valor algebraico obtienes para I?',steps:['Batería de 4 V: +4. Batería de 20 V: −20.','A favor de tu corriente supuesta: −6I y −2I.','4 − 6I − 20 − 2I = 0.','−16 = 8I → I = −2 A.','La corriente real es de 2 A en sentido horario. La solución física es la misma.']},{title:'Ley de nodos: corrientes que entran y salen',tag:'Nivel 1',desc:'En un nodo entran I₁ = 3 A e I₂ = 2 A; sale I₃.',value:5,unit:'A',ask:'¿Cuánto vale I₃?',steps:['Identifica las flechas respecto al nodo.','Entran I₁ e I₂; sale I₃.','I₁ + I₂ = I₃.','I₃ = 3 + 2 = 5 A.']},{title:'Tres ramas: simulacro 2, ejercicio 4',tag:'Nivel 3',desc:'Usa el circuito de la pestaña Nodos y conserva sus flechas I₁, I₂ e I₃. Calcula I₁; en la solución encontrarás también I₂ e I₃.',value:2,unit:'A',ask:'¿Cuánto vale I₁ hacia la derecha?',steps:['En c: I₁ + I₂ = I₃.','Malla superior b→e→f→c→b: −4I₂ −14 +6I₁ −10 = 0 → 6I₁ −4I₂ = 24. En la rama superior, I₂ corresponde a b→e→f→c.','Malla inferior b→c→d→a→b: +10 −6I₁ −2I₃ = 0 → 6I₁ +2I₃ = 10.','Sustituye I₃ = I₁ + I₂: 8I₁ +2I₂ = 10. Multiplica por 2: 16I₁ +4I₂ =20. Suma con 6I₁ −4I₂ =24: 22I₁ =44.','I₁ = 2 A; I₂ = −3 A; I₃ = −1 A. Las corrientes I₂ e I₃ reales apuntan hacia arriba.','Comprueba: 2 +(−3)=−1; 6(2)−4(−3)=24; 6(2)+2(−1)=10.']}];
$('#problem-list').innerHTML=problems.map((p,i)=>`<article class="card problem"><div class="problem-head"><h2>${i+1}. ${p.title}</h2><span class="tag">${p.tag}</span></div><p>${p.desc}</p><label for="answer-${i}">${p.ask}</label><div class="input-row"><input id="answer-${i}" type="number" step="any" placeholder="Tu respuesta"><span>${p.unit}</span><button data-check="${i}">Comprobar</button></div><p id="feedback-${i}" aria-live="polite"></p><details><summary>Ver planteamiento y solución</summary><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details></article>`).join('');
$$('[data-check]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.check),input=$(`#answer-${i}`),f=$(`#feedback-${i}`);if(input.value===''){f.className='bad';f.textContent='Escribe un valor antes de comprobar.';return}const ok=Math.abs(Number(input.value)-problems[i].value)<.01;f.className=ok?'good':'bad';f.textContent=ok?'Correcto. Revisa la solución para comprobar el planteamiento.':'Todavía no coincide. Revisa los signos; puedes abrir la solución paso a paso.'});
$('#print').onclick=()=>window.print();renderLoop();renderNodes();signQuestion();nodeQuestion();
